script:
  - chmod +x run_test.sh
  - chmod +x run_tests.sh
  - ./run_tests.sh t00_hello t01_squirrels t02_squirrels2 t03_last_number t04_first_number t05_tens_number t06_3digits t07_pies t08_watch t09_snail

# disabling email notifications
notifications:
  email: false
  webhooks: http://83.243.70.130:8080/rest/travis/hook